### PR TITLE
add try function in output

### PR DESCRIPTION
**Pull request by wad-hongsumin**
Exception handling so that it can be used even if there is no result

### CODE REVIEW

**Comment by rquadling** [comment]
Hi. Thank you for this. Do you have an example where the AWS output is not valid JSON?

**Comment by rquadling** [comment]
Also, if, somehow, there is content returned that is not valid JSON, would the value be enough to show?

Would this be a good option?
```hcl
try(jsondecode(data.local_file.awscli_results_file.content), data.local_file.awscli_results_file.content)
```

**Comment by horststumpf** [comment]
Hi, the 
"aws ec2 create-tags" 
has no output.

**Comment by rquadling** [comment]
@horststumpf Brilliant. Thank you for that.

**Comment by rquadling** [comment]
I've introduced 2 new outputs.

`output.result_raw = string` and `output.result_was_decoded = bool`.

I suspect these may not be needed much, but rather than attempt to massage broken data, either the data COULD be decoded (and so you can use it), or it was not decoded and you can access the raw value and do your own manipulation as you see fit.

Hopefully that's enough to handle the "bad path" for invalid JSON.

v7.0.0 hopefully coming out today.

Also had to reduce the tests a little as I've not got a public target I can do any interactions with (read only of course).

**Comment by rquadling** [comment]
Thank you @wad-hongsumin. I've incorporated your PR into v7.0.0 and added 2 new outputs to allow non JSON results from the AWS CLI to be accessible as a fallback.

**Pull request closed without merging**
